In [20]:
import numpy as np
import pandas as pd

In [23]:
#1
x=pd.DataFrame([[1,4,3],[3,5,6],[6,7,9]])
y=pd.DataFrame([[1,2,5,12],[6,7,3,0],[4,7,9,11]])
x.dot(y)

0    1    2    3
0  37   51   44   45
1  57   83   84  102
2  84  124  132  171

In [28]:
#2
def extractdivisible3(arr,n):
    remainder=0
    for i in range (0, n): 
        remainder = (remainder + arr[i]) % 3
        return (remainder == 0) 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
n=3
if (extractdivisible3(arr,n)):
    print(arr[i])

NameError: name 'i' is not defined

In [101]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
print(arr[:]%3==0)
      

[ True False False  True False False  True False False  True False False
  True]


In [32]:
3. How to get the unique common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


Object `arrays` not found.
[2 4]


In [41]:

a = np.array([1,2,3,4,5,11,22,33,44,55])
b = np.array([5,6,7,8,9,10,11])
a-b

ValueError: operands could not be broadcast together with shapes (10,) (7,) 

In [40]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [44]:
np.random.randint(10,25,15)

array([24, 15, 21, 18, 23, 23, 19, 19, 13, 17, 14, 23, 23, 15, 13])

In [45]:
np.random.randint(10,25,15).reshape(5,3)

array([[14, 21, 12],
       [10, 13, 10],
       [19, 22, 13],
       [16, 12, 21],
       [10, 21, 21]])

In [51]:
def reverse(s): 
  str = "hello" 
  for i in s: 
    str = i + str
  return str


NameError: name 'hello' is not defined

In [67]:
#8
from array import *
array_num = array('i',[1,7,5,7,2,9,6])
array_num.remove(7)
array_num

array('i', [1, 5, 7, 2, 9, 6])

In [73]:
#9     #https://www.geeksforgeeks.org/python-counter-objects-elements/
from collections import Counter
x = Counter(a=5, b=3, c=0)
print(list(x.elements()))


['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b']


In [76]:
#10   https://www.w3resource.com/python-exercises/collections/python-collections-exercise-4.php
from collections import Counter
import re
text = """Data Science is a domain that includes working with huge amounts of data, developing algorithms, working with machine learning and more to come up with business insights.
It includes working with huge amount of data. Various process are involved to derive the data from source like extracting of data ,cleaning of data , and then converting it into a user desirable format which can be further used information to perform task."""
words = re.findall('\w+',text)
print(Counter(words).most_common(10))


[('data', 5), ('with', 4), ('of', 4), ('working', 3), ('to', 3), ('a', 2), ('includes', 2), ('huge', 2), ('and', 2), ('Data', 1)]


In [77]:
#11 fibanocci
a=0
b=1

In [79]:
n=int(input("Enter the limit o the sereis"))

Enter the limit o the sereis10


In [85]:
print(a,"\n",b)
for i in range(n):
    c=a+b
    a=b
    b=c
    print(c)

0 
 1
1
2
3
5
8
13
21
34
55
89
