# 1.Multiply the two matrices.


In [47]:
import numpy as np

In [48]:
 X = [[1, 4, 3],
      [3, 5, 6],
      [6, 7, 9]]
Y = [[1, 2, 5, 12],
    [6, 7, 3, 0],
    [4, 7, 9, 11]]


In [49]:
result = [[sum(a * b for a, b in zip(X_row, Y_col))  
                        for Y_col in zip(*Y)] 
                                for X_row in X] 
for r in result: 
    print(r) 

[37, 51, 44, 45]
[57, 83, 84, 102]
[84, 124, 132, 171]


# 2. Extract all numbers divisible by 3 from the array


In [50]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
arr=np.where(arr%3 ==0)
arr

(array([ 0,  3,  6,  9, 12], dtype=int64),)

# 3. How to get the unique common items between two python numpy arrays?
Q. Get the unique common items between a and b


In [51]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)

print("c: ",c)

c:  [2 4]


# 4. How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b


In [52]:
import numpy as np

a = np.array([1,2,3,4,5,11,22,33,44,55])
b = np.array([5,6,7,8,9,10,11])
np.setdiff1d(a,b)

array([ 1,  2,  3,  4, 22, 33, 44, 55])

# 5. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match


In [53]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
position=np.where(a==b)
position

(array([1, 3, 5, 7], dtype=int64),)

# 6. How to create a 2D array containing random floats between 10 and 25?
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 10 and 25.


In [54]:
import numpy as np
import random

arr=np.random.uniform(10.0, 25, 15)               #created random array with values btw 10 &25 having 15 elements
arr.reshape(5,3)                                 ##reshaped arr to 2D array


array([[15.78783876, 12.87539576, 10.07621773],
       [11.96013854, 23.22931439, 17.62485869],
       [16.69122983, 19.58361224, 16.38843568],
       [18.18864551, 20.78836091, 24.67120244],
       [15.98576305, 21.1164498 , 10.11738291]])

# 7. Take a string as input. Create a new string that is the reverse of the first string.


In [55]:
str='hari'
str[::-1]

'irah'

# 8. Write a Python program to remove the first occurrence of a specified element  (ex 7 ) from an array.
   Repeat the same for all occurrences of 7

In [56]:
import numpy as np

for x in range(20):
    if x%7 !=0:
        print(x)

1
2
3
4
5
6
8
9
10
11
12
13
15
16
17
18
19


# 9. Write a Python program that iterate over elements repeating each as many times as its count

In [57]:
from collections import Counter
c = Counter(p=4, q=2, r=0, s=-2)
print(list(c.elements()))

['p', 'p', 'p', 'p', 'q', 'q']


In [ ]:
arr=np.arange(10)
