# 1.Multiply the two matrices.
 Input : X = [[1, 4, 3],
             [3, 5, 6],
             [6, 7, 9]]
        Y = [[1, 2, 5, 12],
           [6, 7, 3, 0],
           [4, 7, 9, 11]]


In [10]:
import numpy as np

In [11]:
list1 = [[1,4,3],[3,5,6],[6,7,9]]

In [12]:
list1

[[1, 4, 3], [3, 5, 6], [6, 7, 9]]

In [13]:
list2 = [[1,2,5,12],[6,7,3,10],[4,7,9,11]]

In [14]:
list2

[[1, 2, 5, 12], [6, 7, 3, 10], [4, 7, 9, 11]]

In [15]:
matrix1=np.array(list1)
matrix1

array([[1, 4, 3],
       [3, 5, 6],
       [6, 7, 9]])

In [16]:
matrix2=np.array(list2)
matrix2

array([[ 1,  2,  5, 12],
       [ 6,  7,  3, 10],
       [ 4,  7,  9, 11]])

In [17]:
##res = [[0 for x in range(4)] for y in range(4)] 
result=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]

In [18]:
res=np.array(result)
res

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
for i in range(len(matrix1)): 
    for j in range(len(matrix2[0])): 
        for k in range(len(matrix2)):
            res[i][j] = res[i][j]+ matrix1[i][k] * matrix2[k][j] 
print(res)

[[ 37  51  44  85]
 [ 57  83  84 152]
 [ 84 124 132 241]]


# 2. Extract all numbers divisible by 3 from the array

In [6]:
import numpy as np

In [7]:
list=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12]

In [8]:
n=np.array(list)

In [9]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
for i in range(1,len(n)):
    if (i%3)==0:
        print(n[i])

3
6
9
12


# 3. How to get the unique common items between two python numpy arrays?


In [11]:
import numpy as np

In [12]:
a= np.array([1,2,3,2,3,4,3,4,5,6])

In [13]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [14]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [15]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [16]:
print("Common values between two arrays:")
print(np.intersect1d(a,b))

Common values between two arrays:
[2 4]


# 4. How to remove from one array those items that exist in another?


In [17]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5,11,22,33,44,55])

In [19]:
b = np.array([5,6,7,8,9,10,11])

In [20]:
[x for x in a if x not in b]

[1, 2, 3, 4, 22, 33, 44, 55]

# 5. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match


In [21]:
import numpy as np

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [23]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [24]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

# 6. How to create a 2D array containing random floats between 10 and 25?

In [25]:
import numpy

In [26]:
newArray = numpy.random.randint(10, 25, size=(5,3))
print(newArray)

[[15 22 17]
 [19 18 13]
 [21 17 12]
 [10 13 15]
 [23 11 19]]


# 7. Take a string as input. Create a new string that is the reverse of the first string

In [27]:
str = "chinju"[::-1]
print(str)

ujnihc


# 8. Write a Python program to remove the first occurrence of a specified element  (ex 7 ) from an array.

In [28]:
import numpy as np

In [29]:
list1=[11, 2, 7, 4, 6, 7, 3]
list1

[11, 2, 7, 4, 6, 7, 3]

In [30]:
arr=np.array(list1)
arr

array([11,  2,  7,  4,  6,  7,  3])

In [31]:
arr=arr[arr!=7] ##here modified array.. by removing the repeated value 7
print(arr)

[11  2  4  6  3]


# 9. Write a Python program that iterate over elements repeating each as many times as its count

In [1]:
import numpy as np

In [2]:
for i in range(10):
    print(str(i) * i)


1
22
333
4444
55555
666666
7777777
88888888
999999999


# 10. Write a Python program to find the occurrences of 10 most common words in a given text.

In [4]:
from collections import Counter
text = """The Python interpreter has a number of functions that are always available for use. These functions are called built-in functions. For example, print() function prints the given object to the standard output device (screen) or to the text stream file.The Python interpreter has a number of functions that are always available for use. These functions are called built-in functions. For example, print() function prints the given object to the standard output device (screen) or to the text stream file. """


In [5]:
split_it = text.split() 

In [6]:
Counter = Counter(split_it) 

In [7]:
most_occur = Counter.most_common(10) 

In [8]:
print(most_occur)

[('the', 6), ('functions', 4), ('are', 4), ('to', 4), ('Python', 2), ('interpreter', 2), ('has', 2), ('a', 2), ('number', 2), ('of', 2)]


In [9]:
for wrd in split_it:
    if(len(wrd))==4:
        print (wrd)

that
use.
text
that
use.
text


# 11. Create a python program to generate the Fibonocci series.


In [17]:
i = 0
First_Value = 0
Second_Value = 1

In [49]:
while(i < Number):
           if(i <= 1):
                      Next = i
           else:
                      Next = First_Value + Second_Value
                      First_Value = Second_Value
                      Second_Value = Next
           print(Next)
           i = i + 1

NameError: name 'Number' is not defined